### ISSUE TITLE
image rendering error

### ISSUE THREAD

**Issue by wdputro** [moccu/django-markymark#18]
Hi, first of all thanks for the work.

So, the issue is particularly on the image rendering.
For example: I write `![](https://mirrors.creativecommons.org/presskit/icons/cc.large.png)` on the MarkDownField.

Strangely, the output (from the inspect element browser tool) is like this:

```html
<img alt="" src="<a href=" https:="" mirrors.creativecommons.org="" presskit="" icons="" cc.large.png"="">
https://mirrors.creativecommons.org/presskit/icons/cc.large.png />
```
-------

One can clearly see that it somehow render each slash into attribute of the `img` tag. Any idea why it happens?

-------

I'm using __Markdown-2.6.11 | django-1.9.13 | django-markymark-1.1.0__ with the extension set to:

```python
MARKYMARK_EXTENSIONS = [
    'markymark.extensions.autolink',
    'markdown.extensions.codehilite',
    'markdown.extensions.fenced_code',
    'markdown.extensions.tables',
]
```

Thanks for the assistance,
WDP

**Comment by stephrdev** [comment]
Fixed in cf7cc58. Thank you for reporting the bug.
