### ISSUE TITLE
Split settings

### ISSUE THREAD

**Issue by stephrdev** [moccu/django-markymark#2]
Currently, if you want to add a extension you have to redefine all CSS and JS files. It would be nice to have some kind of "default" scripts and styles which are always included. These "base" files could be defined as settings to to allow advanced extension but in most cases the default files are needed anyway.

**Comment by EnTeQuAk** [comment]
@stephrdev I fixed this in latest master, would this work for you?

```python
from markymark.defaults import DEFAULT_MARKYMARK_EXTENSIONS 

MARKYMARK_EXTENSIONS = DEFAULT_MARKYMARK_EXTENSIONS + [
    'my.custom.extension'
]
```
