### ISSUE TITLE
Mardownfield issue with two different type of lists

### ISSUE THREAD

**Issue by dsteinel** [moccu/django-markymark#8]
If you have a list with discs and a directly following list with numbers, it is rendered as one list of the same type.

**Comment by Schascha** [comment]
From given occasion ... something new here?

**Comment by stephrdev** [comment]
Nope. Its a python-markdown issue.

**Comment by stephrdev** [comment]
One needs to enable sane_lists extension to fix this. Nothing we can do in markymark.
